image: python:3.5

before_script:
  - uname -a
  - pip3 install -r requirements.txt

stages:
  - test

run_tests:
  stage: test
  environment: development 
  script:
    - chmod +x pinkeys.py
    - python3 test_pinkeys.py
    
